In [42]:
# Load in Libraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [43]:
#Bring in your dataset
df = pd.read_csv('2024-04-10 4_36pm (1).csv')

#convert the data into dummy variables
df1= pd.get_dummies(df,drop_first=True)

In [44]:
#Look at the original data
df.head()

,TEMP,CITY,HUMIDITY,WIND_SPEED,TIME,WIND_DIR,PRESSURE_MB
0,28,Mumbai,84.0,2.2,2024-04-10T20:59:00.223700,N,1008.0
1,34,Kerela,19.0,2.9,2024-04-10T20:59:01.256720,SE,1006.0
2,12,Sikkim,51.0,7.6,2024-04-10T20:59:01.649710,NNE,1019.0
3,24,Bangalore,74.0,10.5,2024-04-10T21:02:40.827930,SE,1015.0
4,28,Mumbai,84.0,2.2,2024-04-10T21:02:41.427621,N,1008.0

In [45]:
#Look at the converted data
df1.head()

,TEMP,HUMIDITY,WIND_SPEED,PRESSURE_MB,CITY_Dehradun,CITY_Kerela,CITY_Mumbai,CITY_Sikkim,TIME_2024-04-10T20:59:01.256720,TIME_2024-04-10T20:59:01.649710,TIME_2024-04-10T21:02:40.827930,TIME_2024-04-10T21:02:41.427621,TIME_2024-04-10T21:02:41.932446,TIME_2024-04-10T21:02:42.297173,TIME_2024-04-10T21:02:42.653909,WIND_DIR_NE,WIND_DIR_NNE,WIND_DIR_SE
0,28,84.0,2.2,1008.0,False,False,True,False,False,False,False,False,False,False,False,False,False,False
1,34,19.0,2.9,1006.0,False,True,False,False,True,False,False,False,False,False,False,False,False,True
2,12,51.0,7.6,1019.0,False,False,False,True,False,True,False,False,False,False,False,False,True,False
3,24,74.0,10.5,1015.0,False,False,False,False,False,False,True,False,False,False,False,False,False,True
4,28,84.0,2.2,1008.0,False,False,True,False,False,False,False,True,False,False,False,False,False,False

In [46]:
#create a regression model
model = LinearRegression()

In [47]:
#create X and Y variables
X = df1.drop('TEMP', axis=1)
y = df1['TEMP']

In [48]:
X_train, X_test, y_train,y_test = train_test_split(X,y)

In [49]:
# fit the model to Learn on the training data
model.fit(X_train,y_train)

LinearRegression()

In [59]:
# Let's see what the coefficients are and their influence on charges
pd.DataFrame(zip(X.columns,model.coef_),columns=['Features','Influence/Coefficients']).\
    sort_values(by='Influence/Coefficients', ascending=False)

                           Features  Influence/Coefficients
16                      WIND_DIR_SE            3.981310e+00
9   TIME_2024-04-10T21:02:40.827930            2.046077e+00
4                       CITY_Kerela            1.846320e+00
7   TIME_2024-04-10T20:59:01.256720            1.836457e+00
0                          HUMIDITY            1.919174e-02
12  TIME_2024-04-10T21:02:42.297173            0.000000e+00
8   TIME_2024-04-10T20:59:01.649710            0.000000e+00
10  TIME_2024-04-10T21:02:41.427621           -1.293464e-14
2                       PRESSURE_MB           -7.175822e-02
5                       CITY_Mumbai           -2.479018e-01
11  TIME_2024-04-10T21:02:41.932446           -8.229385e-01
14                      WIND_DIR_NE           -8.229385e-01
3                     CITY_Dehradun           -8.916410e-01
1                        WIND_SPEED           -1.154345e+00
6                       CITY_Sikkim           -2.863924e+00
13  TIME_2024-04-10T21:02:42.653909           -2.863924e+00
15                     WIND_DIR_NNE           -2.863924e+00

In [53]:
# initialize a new model
model2 = XGBRegressor()
model2.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [54]:
# Let's see what the coefficients are and their influence on charges
pd.DataFrame(zip(X.columns , model2.feature_importances_) , columns=['Features' , 'Influence/Coefficients']).\
    sort_values( by = 'Influence/Coefficients', ascending = False)

                           Features  Influence/Coefficients
1                        WIND_SPEED            9.233516e-01
0                          HUMIDITY            4.082131e-02
2                       PRESSURE_MB            3.582694e-02
16                      WIND_DIR_SE            8.990405e-08
4                       CITY_Kerela            0.000000e+00
5                       CITY_Mumbai            0.000000e+00
6                       CITY_Sikkim            0.000000e+00
7   TIME_2024-04-10T20:59:01.256720            0.000000e+00
3                     CITY_Dehradun            0.000000e+00
9   TIME_2024-04-10T21:02:40.827930            0.000000e+00
10  TIME_2024-04-10T21:02:41.427621            0.000000e+00
11  TIME_2024-04-10T21:02:41.932446            0.000000e+00
12  TIME_2024-04-10T21:02:42.297173            0.000000e+00
13  TIME_2024-04-10T21:02:42.653909            0.000000e+00
14                      WIND_DIR_NE            0.000000e+00
15                     WIND_DIR_NNE            0.000000e+00
8   TIME_2024-04-10T20:59:01.649710            0.000000e+00

In [55]:
# Lets create some predictions
y_pred = model.predict(X_test)

In [56]:
# what is are average error
round(np.sqrt(mean_squared_error(y_test , y_pred)), 1)

7.6